controller_list:
  - name: fake_arm_group_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
initial:  # Define initial robot poses.
  - group: arm_group
    pose: home