arm_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
  gains:
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Rev42
  gains:
    Rev42:
      p: 100
      d: 1
      i: 1
      i_clamp: 1